// Country data for phone number selection and flag display
export type Country = {
    code: string;
    name: string;
    dialCode: string;
};

export const countries: Country[] = [
    {
        code: 'AE',
        dialCode: '+971',
        name: 'United Arab Emirates',
    },
    { code: 'AF', dialCode: '+93', name: 'Afghanistan' },
    { code: 'AL', dialCode: '+355', name: 'Albania' },
    { code: 'AO', dialCode: '+244', name: 'Angola' },
    { code: 'AR', dialCode: '+54', name: 'Argentina' },
    { code: 'AT', dialCode: '+43', name: 'Austria' },
    { code: 'AU', dialCode: '+61', name: 'Australia' },
    {
        code: 'BA',
        dialCode: '+387',
        name: 'Bosnia and Herzegovina',
    },
    { code: 'BD', dialCode: '+880', name: 'Bangladesh' },
    { code: 'BE', dialCode: '+32', name: 'Belgium' },
    { code: 'BG', dialCode: '+359', name: 'Bulgaria' },
    { code: 'BR', dialCode: '+55', name: 'Brazil' },
    {
        code: 'CD',
        dialCode: '+243',
        name: 'Democratic Republic of the Congo',
    },
    { code: 'CH', dialCode: '+41', name: 'Switzerland' },
    { code: 'CI', dialCode: '+225', name: "Côte d'Ivoire" },
    { code: 'CL', dialCode: '+56', name: 'Chile' },
    { code: 'CM', dialCode: '+237', name: 'Cameroon' },
    { code: 'CO', dialCode: '+57', name: 'Colombia' },
    { code: 'CR', dialCode: '+506', name: 'Costa Rica' },
    {
        code: 'CZ',
        dialCode: '+420',
        name: 'Czech Republic',
    },
    { code: 'DE', dialCode: '+49', name: 'Germany' },
    { code: 'DK', dialCode: '+45', name: 'Denmark' },
    { code: 'DZ', dialCode: '+213', name: 'Algeria' },
    { code: 'EC', dialCode: '+593', name: 'Ecuador' },
    { code: 'EE', dialCode: '+372', name: 'Estonia' },
    { code: 'EG', dialCode: '+20', name: 'Egypt' },
    { code: 'ES', dialCode: '+34', name: 'Spain' },
    { code: 'ET', dialCode: '+251', name: 'Ethiopia' },
    { code: 'FI', dialCode: '+358', name: 'Finland' },
    { code: 'FR', dialCode: '+33', name: 'France' },
    { code: 'GB', dialCode: '+44', name: 'United Kingdom' },
    { code: 'GE', dialCode: '+995', name: 'Georgia' },
    { code: 'GH', dialCode: '+233', name: 'Ghana' },
    { code: 'GR', dialCode: '+30', name: 'Greece' },
    { code: 'GT', dialCode: '+502', name: 'Guatemala' },
    { code: 'HK', dialCode: '+852', name: 'Hong Kong' },
    { code: 'HR', dialCode: '+385', name: 'Croatia' },
    { code: 'HU', dialCode: '+36', name: 'Hungary' },
    { code: 'ID', dialCode: '+62', name: 'Indonesia' },
    { code: 'IE', dialCode: '+353', name: 'Ireland' },
    { code: 'IL', dialCode: '+972', name: 'Israel' },
    { code: 'IN', dialCode: '+91', name: 'India' },
    { code: 'IQ', dialCode: '+964', name: 'Iraq' },
    { code: 'IR', dialCode: '+98', name: 'Iran' },
    { code: 'IS', dialCode: '+354', name: 'Iceland' },
    { code: 'IT', dialCode: '+39', name: 'Italy' },
    { code: 'JO', dialCode: '+962', name: 'Jordan' },
    { code: 'JP', dialCode: '+81', name: 'Japan' },
    { code: 'KE', dialCode: '+254', name: 'Kenya' },
    { code: 'KR', dialCode: '+82', name: 'South Korea' },
    { code: 'KW', dialCode: '+965', name: 'Kuwait' },
    { code: 'LB', dialCode: '+961', name: 'Lebanon' },
    { code: 'LK', dialCode: '+94', name: 'Sri Lanka' },
    { code: 'LT', dialCode: '+370', name: 'Lithuania' },
    { code: 'LU', dialCode: '+352', name: 'Luxembourg' },
    { code: 'LV', dialCode: '+371', name: 'Latvia' },
    { code: 'MA', dialCode: '+212', name: 'Morocco' },
    { code: 'MD', dialCode: '+373', name: 'Moldova' },
    { code: 'MX', dialCode: '+52', name: 'Mexico' },
    { code: 'MY', dialCode: '+60', name: 'Malaysia' },
    { code: 'MZ', dialCode: '+258', name: 'Mozambique' },
    { code: 'NG', dialCode: '+234', name: 'Nigeria' },
    { code: 'NI', dialCode: '+505', name: 'Nicaragua' },
    { code: 'NL', dialCode: '+31', name: 'Netherlands' },
    { code: 'NO', dialCode: '+47', name: 'Norway' },
    { code: 'NP', dialCode: '+977', name: 'Nepal' },
    { code: 'NZ', dialCode: '+64', name: 'New Zealand' },
    { code: 'PA', dialCode: '+507', name: 'Panama' },
    { code: 'PE', dialCode: '+51', name: 'Peru' },
    { code: 'PH', dialCode: '+63', name: 'Philippines' },
    { code: 'PK', dialCode: '+92', name: 'Pakistan' },
    { code: 'PL', dialCode: '+48', name: 'Poland' },
    { code: 'PT', dialCode: '+351', name: 'Portugal' },
    { code: 'PY', dialCode: '+595', name: 'Paraguay' },
    { code: 'QA', dialCode: '+974', name: 'Qatar' },
    { code: 'RO', dialCode: '+40', name: 'Romania' },
    { code: 'RS', dialCode: '+381', name: 'Serbia' },
    { code: 'RU', dialCode: '+7', name: 'Russia' },
    { code: 'SA', dialCode: '+966', name: 'Saudi Arabia' },
    { code: 'SD', dialCode: '+249', name: 'Sudan' },
    { code: 'SE', dialCode: '+46', name: 'Sweden' },
    { code: 'SG', dialCode: '+65', name: 'Singapore' },
    { code: 'SI', dialCode: '+386', name: 'Slovenia' },
    { code: 'SK', dialCode: '+421', name: 'Slovakia' },
    { code: 'SV', dialCode: '+503', name: 'El Salvador' },
    { code: 'TH', dialCode: '+66', name: 'Thailand' },
    { code: 'TN', dialCode: '+216', name: 'Tunisia' },
    { code: 'TR', dialCode: '+90', name: 'Turkey' },
    { code: 'TW', dialCode: '+886', name: 'Taiwan' },
    { code: 'TZ', dialCode: '+255', name: 'Tanzania' },
    { code: 'UA', dialCode: '+380', name: 'Ukraine' },
    { code: 'UG', dialCode: '+256', name: 'Uganda' },
    { code: 'US', dialCode: '+1', name: 'United States' },
    { code: 'UY', dialCode: '+598', name: 'Uruguay' },
    { code: 'UZ', dialCode: '+998', name: 'Uzbekistan' },
    { code: 'VE', dialCode: '+58', name: 'Venezuela' },
    { code: 'VN', dialCode: '+84', name: 'Vietnam' },
    { code: 'ZA', dialCode: '+27', name: 'South Africa' },
].sort((a, b) => {
    // Remove the '+' and convert to number for proper numeric sorting
    const numA = parseInt(a.dialCode.replace('+', ''));
    const numB = parseInt(b.dialCode.replace('+', ''));
    return numA - numB;
});
