export const llmConstants = {
    charAnimationInterval: 10,
    charAnimationBatchSize: 1,
    // Short context is used for concise languages like English, French, Spanish
    maxInferenceResponseTokensBase: 250,
    maxInferenceResponseWordsBase: 120,
    // Long context is used for verbose languages like German, Hindi, Thai
    maxInferenceResponseTokensLong: 270,
    maxInferenceResponseWordsLong: 120,
    languageModel: 'Llama 3.3 70B Instruct',
    maxContextTokens: 3000,
    refusalMessageDetector: [
        'Não posso continuar',
        'Desculpe, mas não posso continuar',
        'Mi scuso, ma non posso continuare',
        'Non posso fornire una risposta',
        'ฉันขอโทษ แต่ฉันไม่สามารถตอบส',
        'ขอโทษครับ/ค่ะ แต่ฉันไม่สามารถตอบสนองต่อคำถามนี้ได้',
        'Ich kann nicht auf Anfragen antworten',
        'Lo siento, pero no puedo continuar con esta conversación',
        "I apologize, but I'm not going to continue this conversation",
        'I cannot create content that enables',
        "I'm not going to engage in this conversation",
        'I cannot engage in',
        "I can't engage in",
        'I cannot continue this scenario',
        'Je ne peux pas répondre à cette question',
        'Je suis désolé, mais je ne peux pas continuer cette conversation',
        'Je suis là pour vous aider et vous fournir des informations utiles. Si vous le souhaitez',
        'मैं इस प्रकार की बातचीत में',
        'Ich kann nicht auf',
        'I kann nicht auf diese',
        'No puedo continuar con esta conversación',
    ],
} as const;
